<?php
function state_poll_menu() {
    $items = array();
    $items['state_form'] = array(
            'title' => 'State Poll',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('state_poll_form'),
        );
    $items['state_poll_success_page'] = array(
            'title' => 'State Poll Results',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'display_poll_results',
        );
    return $items;
}

function state_poll_form() {
    $form = array();
    $form['ice_cream'] = array(
        '#title' => "What's your favorite ice cream flavor?",
        '#type' => 'textfield',
        '#description' => t("Enter your favorite ice cream flavor"),
        '#required' => TRUE,
    );
    $form['state'] = array(
        '#title' => 'What state are you from?',
        '#type' => 'textfield',
        '#description' => t("Enter what state you're from."),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_length'),
        );
    $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );
    return $form;
}

function element_validate_length($element) {
    if (strlen($element['#value']) === 1 || strlen($element['#value']) === 3) {
        form_error($element, t('State must be either the two-letter abbreviation or full state name!'));
    }
}

// function element_validate_state($element) {
//     if ()
// }

function state_poll_form_submit($form, &$form_state) {
    $ice_cream = $form_state['values']['ice_cream'];
    $state = $form_state['values']['state'];

    $_SESSION['poll_results'] = "Thank you! We have you down for $ice_cream in the state of $state!";

    $form_state['redirect'] = 'state_poll_success_page';
}

function display_poll_results() {
    $results = $_SESSION['poll_results'];

    return $results;
}
