<?php
function ping_pong_menu() {
    $items = array();
    $items['ping_pong'] = array(
        'title' => 'Ping Pong',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ping_pong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['ping_pong_success_page'] = array(
            'title' => 'Ping Pong Success',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'ping_pong_success',
        );
    return $items;
}

function ping_pong_form() {
    $form['count_goal'] = array(
        '#title' => 'Ping Pong changes numbers divisible by 3 into Ping, numbers divisible by 5 into Pong, and numbers divisible by both into PingPong!',
        '#type' => 'textfield',
        '#description' => t('Please enter a number you want to count up to'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Start Ping Pong!!!'
    );

    return $form;
}

function ping_pong_form_submit($form, &$form_state) {

    $count_max = $form_state['values']['count_goal'];
    $pingpong_output = array();

    for ($i=1; $i <= $count_max; $i++) {
        if ($i % 3 == 0 && $i % 5 == 0) {
            array_push($pingpong_output, "PingPong");
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "Ping");
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "Pong");
        } else {
            array_push($pingpong_output, $i);
        }
    }

    $_SESSION['ping_pong_output'] = $pingpong_output;
    $form_state['redirect'] = 'ping_pong_success_page';
}

function ping_pong_success() {
    $output = '<ul>';
    foreach ($_SESSION['ping_pong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';
    }
    $output = $output . '</ul>';
    return "$output";
}
