<?php

function hello_user_menu() {
  $items = array();
  $items['hello_user'] = array(
          'title' => "Hello New User!",
          'page callback' => 'greet_new_user',
          'access callback' => TRUE,
          'type' => MENU_CALLBACK,
      );
  return $items;
}

function greet_new_user() {
    return '<p>Welcome new user!</p>';
}

function hello_user_user_insert(&$edit, $account, $category) {
    $_GET['destination'] = 'hello_user';
}
